templating-4-j:
#  name: templating-4-j-sample
  simulate: true
server:
    port: 8081


spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/templatedb
        username: postgres
        password: 2002
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                enable_lazy_load_no_trans: true


app:
    template:
        root: src/main/resources/templates/
    pdf-file:
        root: src/main/resources/pdf/
